/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_recursoshumanos;

import javax.swing.JOptionPane;

/**
 *
 * @author hondu
 */
public class CambiarPassword_frm extends javax.swing.JPanel {
    ConexionBD con = new ConexionBD();
    /**
     * Creates new form CambiarPassword_frm
     */
    public CambiarPassword_frm() {
        initComponents();
       
        usuario_tf.setText(ConexionBD.usuario);
        oldPass_pf.setTransferHandler(null);
        newPass_pf.setTransferHandler(null);
        rePass_pf.setTransferHandler(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usuario_tf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        oldPass_lbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rePass_pf = new javax.swing.JPasswordField();
        oldPass_pf = new javax.swing.JPasswordField();
        newPass_pf = new javax.swing.JPasswordField();
        Cambiar_btn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Confirmar Contrseña :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

        usuario_tf.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        usuario_tf.setEnabled(false);
        add(usuario_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 270, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setText("Codigo Usuario");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        oldPass_lbl.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        oldPass_lbl.setText("Antigua Contraseña:");
        add(oldPass_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setText("Nueva Contraseña :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        rePass_pf.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        rePass_pf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rePass_pfKeyTyped(evt);
            }
        });
        add(rePass_pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 270, -1));

        oldPass_pf.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        oldPass_pf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                oldPass_pfKeyTyped(evt);
            }
        });
        add(oldPass_pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 270, -1));

        newPass_pf.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        newPass_pf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newPass_pfKeyTyped(evt);
            }
        });
        add(newPass_pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 270, -1));

        Cambiar_btn.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        Cambiar_btn.setText("Cambiar");
        Cambiar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cambiar_btnActionPerformed(evt);
            }
        });
        add(Cambiar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 140, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void Cambiar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cambiar_btnActionPerformed
        // TODO add your handling code here:
        String [] errores = new String[5];
        Integer cant=0;
        if(!oldPass_pf.getText().matches("^\\w*$")){
            errores[cant]="Ingrese un dato en el campo antigua contraseña";
            cant++;
            oldPass_pf.setText("");
        }
        if(!newPass_pf.getText().matches("^(\\w{8,})*$")){
            errores[cant]="Ingrese una contraseña minimo a 8 caracteres";
            cant++;
            newPass_pf.setText("");
             
        }
        if(!newPass_pf.getText().equals(rePass_pf.getText())){
            errores[cant]="Las contraseñas ingresadas no coinciden";
            cant++;
            rePass_pf.setText("");
        }
        if((con.AntiguaPassword(usuario_tf.getText(), oldPass_pf.getText()))!=1){
            errores[cant]="Su contraseña antigua no coincide";
            cant++;
            oldPass_pf.setText("");
        }
        if(cant!=0){
            JOptionPane.showMessageDialog(null, errores);
        }
        else{
             con.CambiarPassword(usuario_tf.getText(), newPass_pf.getText());
             newPass_pf.setText("");
             oldPass_pf.setText("");
             rePass_pf.setText("");
             
        }
        /*
        if(usuario_tf.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Escoja un usuario a modificar");
        }
        else{
            if(Integer.parseInt(ConexionBD.Nivel_Autoridad)<=2){
                if(newPass_pf.getText().equals("") || rePass_pf.getText().equals("")){
                    JOptionPane.showMessageDialog(null,"Rellene los campos necesarios");
                }
                else{
                    if(!newPass_pf.getText().matches("^(\\w{8,})*$") && !rePass_pf.getText().matches("^(\\w{8,})*$"))
                    {
                        if(newPass_pf.getText().equals(rePass_pf.getText()))
                    {
                         con.CambiarPassword(usuario_tf.getText(), newPass_pf.getText());
                            usuario_tf.setText("");
                            newPass_pf.setText("");
                            oldPass_pf.setText("");
                            rePass_pf.setText("");
                    }
                     
                    else{
                        JOptionPane.showMessageDialog(null,"Ingrese Contraseñas iguales");
                    }
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Ingrese una contraseña con 8 caracteres minimo");
                    }
                }
            }
            else{
                if(newPass_pf.getText().equals("") || rePass_pf.getText().equals("") || oldPass_pf.getText().equals("")){
                   JOptionPane.showMessageDialog(null,"Rellene los campos necesarios"); 
                }
                if((con.AntiguaPassword(usuario_tf.getText(), oldPass_pf.getText()))==1){
                    if(newPass_pf.getText().equals(rePass_pf.getText())){
                         con.CambiarPassword(usuario_tf.getText(), newPass_pf.getText());
                        newPass_pf.setText("");
                        oldPass_pf.setText("");
                        rePass_pf.setText("");
                    }
                    
                    else{
                        JOptionPane.showMessageDialog(null,"Ingrese Contraseñas iguales");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Su antigua contraseña no coincide");
                }
            }
        }*/
    }//GEN-LAST:event_Cambiar_btnActionPerformed

    private void newPass_pfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPass_pfKeyTyped
        // TODO add your handling code here:
        if (!(Character.isLetter(evt.getKeyChar())) && !(Character.isDigit(evt.getKeyChar())))
        {
            evt.consume();              
        }
        if (newPass_pf.getPassword().length >= 30)
        {
            evt.consume();                
        }

    }//GEN-LAST:event_newPass_pfKeyTyped

    private void rePass_pfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rePass_pfKeyTyped
        // TODO add your handling code here:
        if (!(Character.isLetter(evt.getKeyChar())) && !(Character.isDigit(evt.getKeyChar())))
        {
            evt.consume();
        }
        if (rePass_pf.getPassword().length >= 30)
        {
            evt.consume();                
        }
    }//GEN-LAST:event_rePass_pfKeyTyped

    private void oldPass_pfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oldPass_pfKeyTyped
        // TODO add your handling code here:
        if (!(Character.isLetter(evt.getKeyChar())) && !(Character.isDigit(evt.getKeyChar())))
        {
            evt.consume();
        }
        if (oldPass_pf.getPassword().length >= 30)
        {
            evt.consume();                
        }
    }//GEN-LAST:event_oldPass_pfKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cambiar_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField newPass_pf;
    private javax.swing.JLabel oldPass_lbl;
    private javax.swing.JPasswordField oldPass_pf;
    private javax.swing.JPasswordField rePass_pf;
    private javax.swing.JTextField usuario_tf;
    // End of variables declaration//GEN-END:variables
}
