/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_recursoshumanos;


import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/**
 *
 * @author jesal
 */
public class ConsultaEmpleados extends javax.swing.JPanel {
       ConexionBD con = new ConexionBD();
       int controlador=0;
    /**
     * Creates new form ConsultaEmpleados
     */
    public ConsultaEmpleados() {
        initComponents();
        btnDatosPersonales.setVisible(false);
        btnDatosPersonales1.setVisible(false);
        btnDatosPersonales1.setEnabled(false);
        //this.setLayout();
       
        JTableHeader header = tblEmpleados.getTableHeader();
        header.setFont(new Font("Centhury Gothic", Font.PLAIN, 14));
        MostrarDatosEmpleados(controlador);
        cargarComboboxfiltro(controlador);

        
        
        if(Integer.parseInt(ConexionBD.Nivel_Autoridad)==1){
           btnDatosPersonales.setVisible(true);
        } 
        else
        {
            btnDatosPersonales1.setVisible(true);
            btnDatosPersonales.setEnabled(false);
        }
    }
    public void MostrarDatosEmpleados(int filtro)
    {
        tblEmpleados.setModel(con.MostrarDatosEmpleados(filtro));
    }
    
    public void cargarComboboxfiltro(int filtro)
    {
          DefaultComboBoxModel combo1 = new DefaultComboBoxModel();
          if(filtro==0)
          {
              combo1.addElement("Puesto");
              combo1.addElement("Estado");
              
          }
          if(filtro==1)
          {
              combo1.addElement("Genero");
          }
          ComboFiltro.setModel(combo1);
          ComboFiltro.setSelectedIndex(-1);
          combofiltrox.setSelectedIndex(-1);
    }
    public void cargarComboboxfiltrox(String filtro){
          if("Puesto".equals(filtro))
          {
              combofiltrox.setModel(con.cargarComboPuesto());
          }
           if("Estado".equals(filtro))
          {
              combofiltrox.setModel(con.cargarComboEstado());
          }
            if("Genero".equals(filtro))
          {
              combofiltrox.setModel(con.cargarComboGenero());
          }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtDisplayInfo = new javax.swing.JLabel();
        ComboFiltro = new javax.swing.JComboBox<>();
        combofiltrox = new javax.swing.JComboBox<>();
        btnDatosPersonales = new javax.swing.JButton();
        btnDatosPersonales1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1030, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEmpleados = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblEmpleados.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblEmpleados.setRowHeight(30);
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 100, 930, 340));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Consulta de Empelados");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 13, -1, -1));

        txtDisplayInfo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtDisplayInfo.setText("Datos Generales del Empleado");
        add(txtDisplayInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 48, -1, -1));

        ComboFiltro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        ComboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboFiltroActionPerformed(evt);
            }
        });
        add(ComboFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 464, 199, -1));

        combofiltrox.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        combofiltrox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(combofiltrox, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 464, 200, -1));

        btnDatosPersonales.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnDatosPersonales.setText("Mostrar Datos Personales");
        btnDatosPersonales.setToolTipText("");
        btnDatosPersonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosPersonalesActionPerformed(evt);
            }
        });
        add(btnDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, -1, -1));

        btnDatosPersonales1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnDatosPersonales1.setText("Mostrar Datos Generales");
        btnDatosPersonales1.setToolTipText("");
        btnDatosPersonales1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosPersonales1ActionPerformed(evt);
            }
        });
        add(btnDatosPersonales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Filtrar Por:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 467, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Filtro:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 467, -1, -1));

        btnFiltrar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private void btnDatosPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosPersonalesActionPerformed
        // TODO add your handling code here:
        controlador=1;
        MostrarDatosEmpleados(controlador);
        cargarComboboxfiltro(controlador);
        btnDatosPersonales.setVisible(false);
        btnDatosPersonales1.setVisible(true);
        btnDatosPersonales1.setEnabled(true);
         txtDisplayInfo.setText("Datos Personales del Empleado");
    }//GEN-LAST:event_btnDatosPersonalesActionPerformed

    private void btnDatosPersonales1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosPersonales1ActionPerformed
        // TODO add your handling code here:
        controlador=0;
        MostrarDatosEmpleados(controlador);
        cargarComboboxfiltro(controlador);
        
         txtDisplayInfo.setText("Datos Generales del Empleado");
        if(Integer.parseInt(ConexionBD.Nivel_Autoridad)==1){
           btnDatosPersonales.setVisible(true);
           btnDatosPersonales1.setVisible(false);
        }
        else
        {
           btnDatosPersonales1.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnDatosPersonales1ActionPerformed

    private void ComboFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboFiltroActionPerformed
        // TODO add your handling code here:

        cargarComboboxfiltrox(String.valueOf(ComboFiltro.getSelectedItem()));
    }//GEN-LAST:event_ComboFiltroActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
           
               // TODO add your handling code here:
             String d1;
             Integer d2;
             d1=String.valueOf(ComboFiltro.getSelectedItem());
             d2=combofiltrox.getSelectedIndex()+1;
           if(d2<1)
           {
               JOptionPane.showMessageDialog(null, "ERROR, seleccione los filtros adecuados", "ERROR",0);
           }
           else{
              try {
               tblEmpleados.setModel(con.filtrarEmpleados(controlador, d1, d2));
           } catch (SQLException ex) {
               Logger.getLogger(ConsultaEmpleados.class.getName()).log(Level.SEVERE, null, ex);
           }
                   JOptionPane.showMessageDialog(null, "Elementos Filtrados con Éxito", "Exito",1); 
           }
            btnDatosPersonales1.setEnabled(true);
           

    }//GEN-LAST:event_btnFiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboFiltro;
    private javax.swing.JButton btnDatosPersonales;
    private javax.swing.JButton btnDatosPersonales1;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox<String> combofiltrox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JLabel txtDisplayInfo;
    // End of variables declaration//GEN-END:variables
}
