/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_recursoshumanos;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hondu
 */
public class Consultas_frm extends javax.swing.JPanel {

    /**
     * Creates new form Consultas_frm
     */
    public Consultas_frm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        empleado_btn = new javax.swing.JButton();
        usuario_btn = new javax.swing.JButton();
        consultas_panel = new javax.swing.JLayeredPane();

        jPanel1.setBackground(new java.awt.Color(255, 0, 7));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empleado_btn.setBackground(new java.awt.Color(215, 0, 5));
        empleado_btn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        empleado_btn.setForeground(new java.awt.Color(255, 255, 255));
        empleado_btn.setText("Empleados");
        empleado_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        empleado_btn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        empleado_btn.setName(""); // NOI18N
        empleado_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado_btnActionPerformed(evt);
            }
        });
        jPanel1.add(empleado_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        usuario_btn.setBackground(new java.awt.Color(215, 0, 5));
        usuario_btn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        usuario_btn.setForeground(new java.awt.Color(255, 255, 255));
        usuario_btn.setText("Usuarios");
        usuario_btn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        usuario_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuario_btnActionPerformed(evt);
            }
        });
        jPanel1.add(usuario_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 190, 60));

        javax.swing.GroupLayout consultas_panelLayout = new javax.swing.GroupLayout(consultas_panel);
        consultas_panel.setLayout(consultas_panelLayout);
        consultas_panelLayout.setHorizontalGroup(
            consultas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        consultas_panelLayout.setVerticalGroup(
            consultas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(consultas_panel)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultas_panel))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void empleado_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado_btnActionPerformed
        // TODO add your handling code here:
        ConsultaEmpleados conEmp = new ConsultaEmpleados();
        Design estetica = new Design();
        estetica.AbrirFormulario(consultas_panel, conEmp);
    }//GEN-LAST:event_empleado_btnActionPerformed

    private void usuario_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario_btnActionPerformed
        try {
            // TODO add your handling code here:
            ConsultaU  conUS = new ConsultaU();
            Design estetica = new Design();
            estetica.AbrirFormulario(consultas_panel, conUS);
        } catch (SQLException ex) {
            Logger.getLogger(Consultas_frm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_usuario_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane consultas_panel;
    private javax.swing.JButton empleado_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton usuario_btn;
    // End of variables declaration//GEN-END:variables
}
