/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_recursoshumanos;

import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/**
 *
 * @author jesal
 */
public class ConsultaU extends javax.swing.JPanel {
    ConexionBD con = new ConexionBD();
    Integer nivel=2;
    /**
     * Creates new form ConsultaU
     */
    public ConsultaU() throws SQLException {
        initComponents();
        btnFiltrar1.setVisible(false);
        if(Integer.parseInt(ConexionBD.Nivel_Autoridad)==1){
           nivel=1;
        } 
        else
        {
            nivel=2;
        }
        JTableHeader header = tblEmpleados.getTableHeader();
        header.setFont(new Font("Centhury Gothic", Font.PLAIN, 14));
        MostrarDatosUsuarios(nivel);
        cargarComboboxfiltro(nivel);
    }
      public void MostrarDatosUsuarios(int filtro)
    {
        Integer d1 = 1;
        String obs="nada";
        try {
            tblEmpleados.setModel(con.filtrarymostrarusuarios(nivel,obs, d1));
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaU.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    

     public void cargarComboboxfiltro(int filtro)
    {
          DefaultComboBoxModel combo1 = new DefaultComboBoxModel();
          if(filtro==1)
          {
              combo1.addElement("Acceso");
              combo1.addElement("Estado");
          }
           if(filtro==2)
          {
              combo1.addElement("Estado");
          }
          
              

          ComboFiltro.setModel(combo1);
          ComboFiltro.setSelectedIndex(-1);
          combofiltrox.setSelectedIndex(-1);
    }
    public void cargarComboboxfiltrox(String filtro){
          if("Acceso".equals(filtro))
          {
              combofiltrox.setModel(con.cargarComboAcceso());
          }
           if("Estado".equals(filtro))
          {
              combofiltrox.setModel(con.cargarComboEstado());
          }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ComboFiltro = new javax.swing.JComboBox<>();
        btnFiltrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        combofiltrox = new javax.swing.JComboBox<>();
        btnFiltrar1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Consulta de Usuarios");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        tblEmpleados = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblEmpleados.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblEmpleados.setRowHeight(30);
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 100, 930, 340));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Filtrar Por:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 467, -1, -1));

        ComboFiltro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        ComboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboFiltroActionPerformed(evt);
            }
        });
        add(ComboFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 464, 199, -1));

        btnFiltrar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 200, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Filtro:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, -1, -1));

        combofiltrox.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        combofiltrox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(combofiltrox, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 200, -1));

        btnFiltrar1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnFiltrar1.setText("Retirar Filtro");
        btnFiltrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrar1ActionPerformed(evt);
            }
        });
        add(btnFiltrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private void ComboFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboFiltroActionPerformed
        // TODO add your handling code here:

        cargarComboboxfiltrox(String.valueOf(ComboFiltro.getSelectedItem()));
    }//GEN-LAST:event_ComboFiltroActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed

        // TODO add your handling code here:
        String d1;
        Integer d2;
        d1=String.valueOf(ComboFiltro.getSelectedItem());
        d2=combofiltrox.getSelectedIndex()+1;
        if(d2<1)
        {
            JOptionPane.showMessageDialog(null, "ERROR, seleccione los filtros adecuados", "ERROR",0);
        }
        else{
            try {
                tblEmpleados.setModel(con.filtrarymostrarusuarios(nivel,d1,d2));
            } catch (SQLException ex) {
                Logger.getLogger(ConsultaU.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Elementos Filtrados con Éxito", "Exito",1);
             btnFiltrar1.setVisible(true);
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnFiltrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrar1ActionPerformed
        // TODO add your handling code here:
        MostrarDatosUsuarios(nivel);
         btnFiltrar1.setVisible(false);
         ComboFiltro.setSelectedIndex(-1);
         combofiltrox.setSelectedIndex(-1);
    }//GEN-LAST:event_btnFiltrar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboFiltro;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnFiltrar1;
    private javax.swing.JComboBox<String> combofiltrox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmpleados;
    // End of variables declaration//GEN-END:variables
}
