/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_recursoshumanos;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jesal
 */
public class Despido_Renuncia_Empleados extends javax.swing.JPanel {

    ConexionBD con = new ConexionBD();
    public Integer control;
    /**
     * Creates new form Despido_Renuncia_Empleados
     */
    public Despido_Renuncia_Empleados() {
        initComponents();
        txtprest.setVisible(false);
        labelprest.setVisible(false);
        btnRegistrar.setVisible(false);
        txtIdentidad.setEditable(false);
        txtNombre.setEditable(false);
        txtSalario.setEditable(false);
        txtprest.setEditable(false);
        mostrarDatosEmpleados();
    }
    
    public void mostrarDatosEmpleados(){
        tblEmpleados.setModel(con.MostrarDatosEmpleadosRenuncia());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdentidad = new javax.swing.JTextField();
        acceso_lbl = new javax.swing.JLabel();
        cmbAcciones = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        txtPorcPrestaciones = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        labelprest = new javax.swing.JLabel();
        txtprest = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEmpleados = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblEmpleados.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblEmpleados.setRowHeight(30);
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 950, 150));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Renuncia / Despido de Empleados");
        jLabel1.setToolTipText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Identidad");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        txtIdentidad.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        add(txtIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 392, -1));

        acceso_lbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        acceso_lbl.setText("Acción");
        add(acceso_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        cmbAcciones.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cmbAcciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Renuncia", "Despido" }));
        cmbAcciones.setSelectedIndex(-1);
        cmbAcciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAccionesActionPerformed(evt);
            }
        });
        add(cmbAcciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 392, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 392, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Salario");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        txtSalario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 392, -1));

        txtPorcPrestaciones.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPorcPrestaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPorcPrestacionesKeyTyped(evt);
            }
        });
        add(txtPorcPrestaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 392, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("% de Prestaciones");
        jLabel5.setToolTipText("");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        labelprest.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        labelprest.setText("Prestaciones");
        add(labelprest, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, -1, -1));
        labelprest.getAccessibleContext().setAccessibleName("Prestaciones:");

        txtprest.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        add(txtprest, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 392, -1));

        btnRegistrar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnRegistrar.setText("Registrar Renuncia");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, 302, 50));

        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton2.setText("Calcular Prestaciones");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 302, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        // TODO add your handling code here:
        txtIdentidad.setText(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(),0).toString());
        txtNombre.setText(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(),1).toString());
        txtSalario.setText(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow(),3).toString());
        
    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:4
        String confirmacion;
        Double suma = Double.parseDouble(txtSalario.getText())+Double.parseDouble(txtprest.getText());
        {
            confirmacion = JOptionPane.showInputDialog(null,"Esta a punto de hacer cambios importante a "+txtNombre.getText()+" que costaran a la empresa Lps."+suma+"\n\n\t Escribar CONFIRMAR para proseguir.", "Confirmación", 1);
            if("CONFIRMAR".equals(confirmacion))
            {
                try {
                    con.RenunciaDespido(txtIdentidad.getText(),control, suma);
                } catch (SQLException ex) {
                    Logger.getLogger(Despido_Renuncia_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                }
                txtIdentidad.setText("");
                txtNombre.setText("");
                txtSalario.setText("");
                txtPorcPrestaciones.setText("");
                txtprest.setText("");
                cmbAcciones.setSelectedIndex(-1);
                txtprest.setVisible(false);
                labelprest.setVisible(false);
                btnRegistrar.setVisible(false);
                mostrarDatosEmpleados();
                
            }
            else
            {
                 JOptionPane.showMessageDialog(null, "Cambios Cancelados", "Cancelado",1);
            }
           
        }

        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if("".equals(txtIdentidad.getText()) ||"".equals(txtNombre.getText())||"".equals(txtSalario.getText())||"".equals(txtPorcPrestaciones.getText()))
        {
            JOptionPane.showMessageDialog(null, "ERROR, ningun campo de texto puede quedar vacio", "ERROR",0);
        }
        else
        if(cmbAcciones.getSelectedIndex()==-1)
        {
            JOptionPane.showMessageDialog(null, "ERROR, Debe seleccionar una accion a realizar", "ERROR",0);
        }
        else
        if(Double.parseDouble(txtPorcPrestaciones.getText())<25.0 ||Double.parseDouble(txtPorcPrestaciones.getText())>1000.0  ||!txtPorcPrestaciones.getText().matches("^([1-9]{1})([0-9]{1,2})?$"))
        {
            JOptionPane.showMessageDialog(null, "ERROR, El porcentaje de Prestaciones no puede ser menor que 25%, ni mayor que 1000%", "ERROR",0);
            txtPorcPrestaciones.setText("");
        }
        else
            {
                txtprest.setText(Double.toString(Double.parseDouble(txtSalario.getText())*Double.parseDouble(txtPorcPrestaciones.getText())/100));
                txtprest.setVisible(true);
                labelprest.setVisible(true);
                btnRegistrar.setVisible(true);
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbAccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAccionesActionPerformed
        // TODO add your handling code here:
        if(cmbAcciones.getSelectedIndex()==0)
        {
            txtPorcPrestaciones.setText("25");
            control=4;
        }
        if(cmbAcciones.getSelectedIndex()==1)
        {
            txtPorcPrestaciones.setText("50");
            control=3;
        }
    }//GEN-LAST:event_cmbAccionesActionPerformed

    private void txtPorcPrestacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcPrestacionesKeyTyped
        // TODO add your handling code here:
        String valNom ="[0-9.]";
        String a=Character.toString(evt.getKeyChar()) ;
            
          if(!a.matches(valNom)|| txtPorcPrestaciones.getText().length()>=3 ){
            evt.consume();
            
        }
    }//GEN-LAST:event_txtPorcPrestacionesKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acceso_lbl;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbAcciones;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelprest;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtIdentidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPorcPrestaciones;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtprest;
    // End of variables declaration//GEN-END:variables
}
