/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_recursoshumanos;

import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/**
 *
 * @author steph
 */
public class ModificarUsuario_frm extends javax.swing.JPanel {
    ConexionBD con = new ConexionBD();
    /**
     * Creates new form ModificarUsuario_frm
     */
    public ModificarUsuario_frm() {
        initComponents();
       
        
        LlenarCombo();
   
            tblUsuario.setVisible(true);
             JTableHeader header = tblUsuario.getTableHeader();
            header.setFont(new Font("Centhury Gothic", Font.PLAIN, 14));
            MostrarUsuarios();
       
    }

    public void MostrarUsuarios()
    {
        tblUsuario.setModel(con.Mostrar());
    }
    
    public void LlenarCombo()
    {
        
        cmbAcceso.setModel(con.cargarComboAcceso());
        cmbEstado.setModel(con.cargarComboEstado());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acceso_lbl = new javax.swing.JLabel();
        estado_lbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        cmbAcceso = new javax.swing.JComboBox<>();
        cmbEstado = new javax.swing.JComboBox<>();

        tblUsuario = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblUsuario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblUsuario.setRowHeight(30);
        tblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuario);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modificar Usuario");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setText("Usuario");

        acceso_lbl.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        acceso_lbl.setText("Acceso");

        estado_lbl.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        estado_lbl.setText("Estado");

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtUsuario.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtUsuario.setEnabled(false);

        cmbAcceso.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        cmbEstado.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel2)
                        .addGap(64, 64, 64)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(acceso_lbl)
                        .addGap(39, 39, 39)
                        .addComponent(cmbAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(estado_lbl)
                                .addGap(261, 261, 261)
                                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acceso_lbl)
                    .addComponent(cmbAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estado_lbl)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuarioMouseClicked
        // TODO add your handling code here:
        txtUsuario.setText(tblUsuario.getValueAt(tblUsuario.getSelectedRow(),0).toString());
        cmbAcceso.setSelectedItem(tblUsuario.getValueAt(tblUsuario.getSelectedRow(),1).toString());
        cmbEstado.setSelectedItem(tblUsuario.getValueAt(tblUsuario.getSelectedRow(),2).toString());
    }//GEN-LAST:event_tblUsuarioMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
        Integer res=0;
        if(txtUsuario.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Escoja un usuario a modifcar");
        }
        else{
            if(cmbAcceso.getSelectedIndex()==-1 || cmbEstado.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null,"Rellene los datos necesarios");
        }
        else{
                if(tblUsuario.getValueAt(tblUsuario.getSelectedRow(),1).toString().equals("Administrador de Sistema de Software")){
                    if(cmbEstado.getSelectedIndex()==1 || cmbAcceso.getSelectedIndex()!=0){
                        JOptionPane.showMessageDialog(null,"No puede desactivar a ese usuario o cambiar su nivel de Acceso");
                         txtUsuario.setText("");
                        cmbAcceso.setSelectedIndex(-1);
                        cmbEstado.setSelectedIndex(-1);

                    }
                   
                }
                else{
                    JOptionPane.showMessageDialog(null,Integer.toString(cmbAcceso.getSelectedIndex()));
                        JOptionPane.showMessageDialog(null,ConexionBD.Nivel_Autoridad);
                        if( cmbAcceso.getSelectedIndex()==0 && ConexionBD.Nivel_Autoridad.equals("1") ){
                            res=JOptionPane.showOptionDialog(null,"Si acepta dejara su puesto como Administrador","ATENCIÓN",JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
                            if(res==JOptionPane.YES_OPTION){
                                try {
                                con.ModificacionUsuario(ConexionBD.usuario, 2, 1);
                                con.ModificacionUsuario(txtUsuario.getText(),cmbAcceso.getSelectedIndex()+1, cmbEstado.getSelectedIndex()+1);
                                JOptionPane.showMessageDialog(null,"Usuario Modificado correctamente");
                                txtUsuario.setText("");
                                cmbAcceso.setSelectedIndex(-1);
                                cmbEstado.setSelectedIndex(-1);

                               } catch (SQLException ex) {
                                   Logger.getLogger(ModificarUsuario_frm.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        }
                        else{
                            try {
                                con.ModificacionUsuario(txtUsuario.getText(),cmbAcceso.getSelectedIndex()+1, cmbEstado.getSelectedIndex()+1);
                                JOptionPane.showMessageDialog(null,"Usuario Modificado correctamente");
                                txtUsuario.setText("");
                                cmbAcceso.setSelectedIndex(-1);
                                cmbEstado.setSelectedIndex(-1);

                               } catch (SQLException ex) {
                                   Logger.getLogger(ModificarUsuario_frm.class.getName()).log(Level.SEVERE, null, ex);
                                }

                        } 
                }
                
            }
        }
        if(Integer.parseInt(ConexionBD.Nivel_Autoridad)==1){
                MostrarUsuarios();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acceso_lbl;
    private javax.swing.JComboBox<String> cmbAcceso;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel estado_lbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
