/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_recursoshumanos;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hondu
 */
public class nuevoUsuario_frm extends javax.swing.JPanel {
     ConexionBD con = new ConexionBD();
    /**
     * Creates new form nuevoUsuario_frm
     */
    public nuevoUsuario_frm() {
        initComponents();
        LlenarCombo();
        if(Integer.parseInt(ConexionBD.Nivel_Autoridad)>=2){
            cbTipoAcceso.removeItem("Administrador de Sistema de Software");
        }
    }
     public void LlenarCombo()
    {
        empleado_tbl.setModel(con.CargarEmpleadosSinUser());
        cbTipoAcceso.setModel(con.cargarComboAcceso());
        cbTipoAcceso.setSelectedIndex(-1);
        //cbEstado.setModel(con.cargarComboEstado());
        //cbEstado.setSelectedIndex(-1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Ingresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbTipoAcceso = new javax.swing.JComboBox<String>();
        codusu = new javax.swing.JTextField();
        pw_pf = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        pw_pf2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        empleado_tf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        empleado_tbl = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setText("Favor Ingresar la Siguiente Informacion");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setText("Creacion de Usuario");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 326, 33));

        Ingresar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        Ingresar.setText("Crear");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 127, 58));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setText("Usuario:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setText("Contraseña:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setText("Tipo de Acceso:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        cbTipoAcceso.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cbTipoAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoAccesoActionPerformed(evt);
            }
        });
        add(cbTipoAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 218, -1));

        codusu.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        codusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codusuActionPerformed(evt);
            }
        });
        codusu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codusuKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codusuKeyTyped(evt);
            }
        });
        add(codusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 218, -1));

        pw_pf.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        pw_pf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pw_pfKeyTyped(evt);
            }
        });
        add(pw_pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 218, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setText("Confirme Contraseña:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        pw_pf2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        pw_pf2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pw_pf2KeyTyped(evt);
            }
        });
        add(pw_pf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 218, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel9.setText("Codigo Empleado:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        empleado_tf.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        empleado_tf.setEnabled(false);
        empleado_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado_tfActionPerformed(evt);
            }
        });
        empleado_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                empleado_tfKeyPressed(evt);
            }
        });
        add(empleado_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 280, -1));

        empleado_tbl = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        empleado_tbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        empleado_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        empleado_tbl.setRowHeight(30);
        empleado_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empleado_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(empleado_tbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 540, 150));
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        
             if(codusu.getText().equals("") || pw_pf.getPassword().equals("") || pw_pf2.getPassword().equals("") || cbTipoAcceso.getSelectedIndex()==-1 ){//|| cbEstado.getSelectedIndex()==-1 ){
                JOptionPane.showMessageDialog(null,"Ingrese los datos requeridos");
             }else{
                if(pw_pf2.getText().equals(pw_pf.getText())){
                   if(con.validacionUsuario(codusu.getText())==0){
                       try {
                         con.CreacionUsuario(empleado_tf.getText(),codusu.getText(),pw_pf.getText(),Integer.toString(cbTipoAcceso.getSelectedIndex()+1), "1");
                      }
                      catch (SQLException ex) {
                        Logger.getLogger(nuevoUsuario_frm.class.getName()).log(Level.SEVERE, null, ex);
                      }
                   }
                   else{
                       JOptionPane.showMessageDialog(null,"Ese usuario ya existe");
                   }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Las contrseñas ingresadas no son igulaes");
                    pw_pf.setText("");
                    pw_pf2.setText("");
                    pw_pf.requestFocus();
                }
             }
      
         
         
     

    }//GEN-LAST:event_IngresarActionPerformed

    private void cbTipoAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoAccesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoAccesoActionPerformed

    private void codusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codusuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codusuActionPerformed

    private void codusuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codusuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_codusuKeyPressed

    private void empleado_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleado_tfActionPerformed

    private void empleado_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empleado_tfKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleado_tfKeyPressed

    private void empleado_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empleado_tblMouseClicked
        // TODO add your handling code here:
        empleado_tf.setText(empleado_tbl.getValueAt(empleado_tbl.getSelectedRow(),0).toString());
        /*cmbAcceso.setSelectedItem(tblUsuario.getValueAt(tblUsuario.getSelectedRow(),1).toString());
        cmbEstado.setSelectedItem(tblUsuario.getValueAt(tblUsuario.getSelectedRow(),2).toString());*/
    }//GEN-LAST:event_empleado_tblMouseClicked

    private void codusuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codusuKeyTyped
        // TODO add your handling code here:
        if (!(Character.isLetter(evt.getKeyChar())) && !(Character.isDigit(evt.getKeyChar())))
        {
            evt.consume();              
        }
        if (codusu.getText().length() >= 30)
        {
            evt.consume();                
        }
    }//GEN-LAST:event_codusuKeyTyped

    private void pw_pfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pw_pfKeyTyped
        // TODO add your handling code here:
        if (!(Character.isLetter(evt.getKeyChar())) && !(Character.isDigit(evt.getKeyChar())))
        {
            evt.consume();              
        }
        if (pw_pf.getPassword().length >= 30)
        {
            evt.consume();                
        }
    }//GEN-LAST:event_pw_pfKeyTyped

    private void pw_pf2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pw_pf2KeyTyped
        // TODO add your handling code here:
        if (!(Character.isLetter(evt.getKeyChar())) && !(Character.isDigit(evt.getKeyChar())))
        {
            evt.consume();              
        }
        if (pw_pf2.getPassword().length >= 30)
        {
            evt.consume();                
        }
    }//GEN-LAST:event_pw_pf2KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingresar;
    private javax.swing.JComboBox<String> cbTipoAcceso;
    private javax.swing.JTextField codusu;
    private javax.swing.JTable empleado_tbl;
    private javax.swing.JTextField empleado_tf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField pw_pf;
    private javax.swing.JPasswordField pw_pf2;
    // End of variables declaration//GEN-END:variables
}
