/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_recursoshumanos;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class nuevoPuesto extends javax.swing.JPanel {
    ConexionBD con = new ConexionBD();
    /**
     * Creates new form nuevoPuesto
     */
    public nuevoPuesto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nompuesto = new javax.swing.JTextField();
        descripcionpuesto = new javax.swing.JTextField();
        crearpuesto = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1030, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Creacion de Puesto");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Ingrese la Siguiente Informacion");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setText("Nombre del Puesto:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setText("Descripcion:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        nompuesto.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        add(nompuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 221, -1));

        descripcionpuesto.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        add(descripcionpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 221, -1));

        crearpuesto.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        crearpuesto.setText("Crear");
        crearpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearpuestoActionPerformed(evt);
            }
        });
        add(crearpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 150, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void crearpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearpuestoActionPerformed
        
            // TODO add your handling code here:
            String [] errores = new String[3];
            Integer cant=0;
            if(!nompuesto.getText().matches("^([a-zA-z]{3,})+([a-zA-Z ]{2,})")){
                errores[cant]="Nombre de Puesto Incorrecto";
                cant++;
                nompuesto.setText(" ");
            }
            if(!descripcionpuesto.getText().matches("^([a-zA-z]{3,})+([a-zA-Z ]{2,})")){
                errores[cant]="Descripcion de Puesto incorrecto";
                cant++;
            }
            if(con.validacionPuesto(nompuesto.getText())>=1){
                errores[cant]="Ese puesto ya existe";
                cant++;
            }
            if(cant!=0){
             
                JOptionPane.showMessageDialog(null,errores);
            }
            else{
                 con.CreacionPuesto(nompuesto.getText(),descripcionpuesto.getText());
            }
           
      
        
        
    }//GEN-LAST:event_crearpuestoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearpuesto;
    private javax.swing.JTextField descripcionpuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nompuesto;
    // End of variables declaration//GEN-END:variables
}
