/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_recursoshumanos;
import java.util.regex.*;
import javax.swing.JOptionPane;
/**
 *
 * @author hondu
 */
public class NuevoEmpleado_frm extends javax.swing.JPanel {
    ConexionBD cone = new ConexionBD();
    /**
     * Creates new form NuevoEmpleado_frm
     */
    public NuevoEmpleado_frm() {
        initComponents();
        ide_tf.setTransferHandler(null);
        nom_tf.setTransferHandler(null);
        dire_tf.setTransferHandler(null);
        correo_tf.setTransferHandler(null);
        sueldo_tf.setTransferHandler(null);
        gen_cmb.setModel(cone.cargarComboGenero());
        gen_cmb.setSelectedIndex(-1);
        puesto_cmb.setModel(cone.cargarComboPuesto());
        puesto_cmb.setSelectedIndex(-1);
        puesto_cmb.removeItem("Administrador de Software");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jLabel1 = new javax.swing.JLabel();
        ide_tf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nom_tf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        correo_tf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sueldo_tf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dire_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        gen_cmb = new javax.swing.JComboBox<>();
        puesto_cmb = new javax.swing.JComboBox<>();
        contratar_btn = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Identidad del Empleado");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        ide_tf.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        ide_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ide_tfKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ide_tfKeyTyped(evt);
            }
        });
        add(ide_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 300, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setText("Nombre Completo");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        nom_tf.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        nom_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nom_tfKeyTyped(evt);
            }
        });
        add(nom_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 300, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setText("Correo Electronico");
        jLabel3.setToolTipText("");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        correo_tf.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        correo_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                correo_tfKeyTyped(evt);
            }
        });
        add(correo_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 300, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setText("Genero");
        jLabel4.setToolTipText("");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        sueldo_tf.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        sueldo_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sueldo_tfKeyTyped(evt);
            }
        });
        add(sueldo_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 300, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setText("Direccion del Empleado");
        jLabel5.setToolTipText("");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        dire_tf.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        dire_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dire_tfKeyTyped(evt);
            }
        });
        add(dire_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 300, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setText("Sueldo del Empleado");
        jLabel6.setToolTipText("");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setText("Puesto");
        jLabel7.setToolTipText("");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        gen_cmb.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        gen_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(gen_cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 290, 40));

        puesto_cmb.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        puesto_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(puesto_cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 290, 40));

        contratar_btn.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        contratar_btn.setText("Contratar");
        contratar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratar_btnActionPerformed(evt);
            }
        });
        add(contratar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 180, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void ide_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ide_tfKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_ide_tfKeyPressed

    private void ide_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ide_tfKeyTyped
        // TODO add your handling code here:
        String valIde ="[0-9]";
        String a=Character.toString(evt.getKeyChar()) ;
            
          if(!a.matches(valIde) || ide_tf.getText().length()>=13 ){
            evt.consume();
        }
    }//GEN-LAST:event_ide_tfKeyTyped

    private void nom_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nom_tfKeyTyped
        // TODO add your handling code here:
        String valNom ="[a-zA-Z ]";
        String a=Character.toString(evt.getKeyChar()) ;
            
          if(!a.matches(valNom)|| nom_tf.getText().length()>=80 ){
            evt.consume();
        }
    }//GEN-LAST:event_nom_tfKeyTyped

    private void correo_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correo_tfKeyTyped
        // TODO add your handling code here:
        String valNom ="[a-zA-Z0-9@._-]";
        String a=Character.toString(evt.getKeyChar()) ;
            
          if(!a.matches(valNom)|| correo_tf.getText().length()>=60 ){
            evt.consume();
        }
    }//GEN-LAST:event_correo_tfKeyTyped

    private void dire_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dire_tfKeyTyped
        // TODO add your handling code here:
        String valNom ="[a-zA-Z .-]";
        String a=Character.toString(evt.getKeyChar()) ;
            
          if(!a.matches(valNom)|| dire_tf.getText().length()>=80 ){
            evt.consume();
        }
    }//GEN-LAST:event_dire_tfKeyTyped

    private void sueldo_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sueldo_tfKeyTyped
        // TODO add your handling code here:
        String valNom ="[0-9.]";
        String a=Character.toString(evt.getKeyChar()) ;
            
          if(!a.matches(valNom)|| sueldo_tf.getText().length()>=100 ){
            evt.consume();
            
        }
    }//GEN-LAST:event_sueldo_tfKeyTyped

    private void contratar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratar_btnActionPerformed
        // TODO add your handling code here:
        String [] errores= new String [5];
        Integer cant=0;
        if(!ide_tf.getText().matches("^[0-9]{13}$")){
        
                errores[cant]="Identidad Incorrecta Digite bien los datos";
                cant++;
        }
        if(!nom_tf.getText().matches("^([a-zA-z]{4,})+([a-zA-Z ]{4,})$")){
            errores[cant]="Nombre Incorrecto";
            cant++;
        }
        if(!correo_tf.getText().matches("^([a-z])+.+[@]+[a-zA-Z.]+(.com)$")){
                errores[cant]="Correo Electronico Incorrecto";
                cant++;
        }
        
        if(!dire_tf.getText().matches("^([a-zA-z]{1,})+.+[a-zA-Z .-_]$")){
        
                errores[cant]="Direccion Incorrecta";
                cant++;
        }
        
        if(!sueldo_tf.getText().matches("^([1-9]{1})+([0-9]{2,})+.??([0-9]{1,})$")){
        
                errores[cant]="Sueldo Incorrecto";
                cant++;
        }        
        if(gen_cmb.getSelectedIndex()==-1){
            errores[cant]="Escoja un genero";
            cant++;
        }
        if(puesto_cmb.getSelectedIndex()==-1){
            errores[cant]="Escoja un puesto";
            cant++;
        }
        if(cone.ValidacionEmpleados(ide_tf.getText())==1){
            errores[cant]="Ya existe ese Empleado";
            cant++;
        }
        if(cant!=0){
            JOptionPane.showMessageDialog(null,errores);
        }
        else{
            cone.NuevoEmpleado(ide_tf.getText(), nom_tf.getText(),correo_tf.getText(), Double.parseDouble(sueldo_tf.getText()), dire_tf.getText(), gen_cmb.getSelectedIndex()+1, puesto_cmb.getSelectedIndex()+1);
        }
            
        
    }//GEN-LAST:event_contratar_btnActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contratar_btn;
    private javax.swing.JTextField correo_tf;
    private javax.swing.JTextField dire_tf;
    private javax.swing.JComboBox<String> gen_cmb;
    private javax.swing.JTextField ide_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nom_tf;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private javax.swing.JComboBox<String> puesto_cmb;
    private javax.swing.JTextField sueldo_tf;
    // End of variables declaration//GEN-END:variables
}
