/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_recursoshumanos;

import javax.swing.JOptionPane;

/**
 *
 * @author hondu
 */
public class Principal_frm extends javax.swing.JFrame {

    private  Design estetica = new Design();
    /**
     * Creates new form Principal_frm
     */
    public Principal_frm() {
        initComponents();// Escondo todos los botones cuando cargar el programa
        bienvenido_lbl.setVisible(false);
        nombre_lbl.setVisible(false);
        empleados_btn.setVisible(false);
        consultas_btn.setVisible(false);
        puesto_btn.setVisible(false);
        usuarios_btn.setVisible(false);
        restart_btn.setVisible(false);
        back_lbl.setVisible(false);
        correo_tf.setVisible(false);
                    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        left_panel = new javax.swing.JPanel();
        restart_btn = new javax.swing.JButton();
        consultas_btn = new javax.swing.JButton();
        puesto_btn = new javax.swing.JButton();
        usuarios_btn = new javax.swing.JButton();
        bienvenido_lbl = new javax.swing.JLabel();
        nombre_lbl = new javax.swing.JLabel();
        empleados_btn = new javax.swing.JButton();
        principal_panel = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        pass_lbl = new javax.swing.JLabel();
        titulo_lbl = new javax.swing.JLabel();
        usuario_tf = new javax.swing.JTextField();
        ingresar_btn = new javax.swing.JButton();
        contra_pf = new javax.swing.JPasswordField();
        olvide_lbl = new javax.swing.JLabel();
        back_lbl = new javax.swing.JLabel();
        correo_tf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left_panel.setBackground(new java.awt.Color(165, 0, 4));
        left_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        restart_btn.setBackground(new java.awt.Color(255, 255, 255));
        restart_btn.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        restart_btn.setForeground(new java.awt.Color(215, 0, 5));
        restart_btn.setText("Cerrar Sesión");
        restart_btn.setIconTextGap(0);
        restart_btn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        restart_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restart_btnActionPerformed(evt);
            }
        });
        left_panel.add(restart_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 620, 280, 90));

        consultas_btn.setBackground(new java.awt.Color(215, 0, 5));
        consultas_btn.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        consultas_btn.setForeground(new java.awt.Color(255, 255, 255));
        consultas_btn.setText("Consultas");
        consultas_btn.setIconTextGap(0);
        consultas_btn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        consultas_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultas_btnActionPerformed(evt);
            }
        });
        left_panel.add(consultas_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 280, 120));

        puesto_btn.setBackground(new java.awt.Color(215, 0, 5));
        puesto_btn.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        puesto_btn.setForeground(new java.awt.Color(255, 255, 255));
        puesto_btn.setText("Puestos");
        puesto_btn.setIconTextGap(0);
        puesto_btn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        puesto_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puesto_btnActionPerformed(evt);
            }
        });
        left_panel.add(puesto_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 280, 120));

        usuarios_btn.setBackground(new java.awt.Color(215, 0, 5));
        usuarios_btn.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        usuarios_btn.setForeground(new java.awt.Color(255, 255, 255));
        usuarios_btn.setText("Usuarios");
        usuarios_btn.setIconTextGap(0);
        usuarios_btn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        usuarios_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarios_btnActionPerformed(evt);
            }
        });
        left_panel.add(usuarios_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 280, 120));

        bienvenido_lbl.setFont(new java.awt.Font("Century Gothic", 0, 44)); // NOI18N
        bienvenido_lbl.setForeground(new java.awt.Color(255, 255, 255));
        bienvenido_lbl.setText("Bienvenido");
        left_panel.add(bienvenido_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        nombre_lbl.setFont(new java.awt.Font("Century Gothic", 2, 24)); // NOI18N
        nombre_lbl.setForeground(new java.awt.Color(255, 255, 255));
        nombre_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_lbl.setText("Nombre");
        left_panel.add(nombre_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        empleados_btn.setBackground(new java.awt.Color(215, 0, 5));
        empleados_btn.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        empleados_btn.setForeground(new java.awt.Color(255, 255, 255));
        empleados_btn.setText("Empleados");
        empleados_btn.setIconTextGap(0);
        empleados_btn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        empleados_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleados_btnActionPerformed(evt);
            }
        });
        left_panel.add(empleados_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 280, 120));

        getContentPane().add(left_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 700));

        principal_panel.setBackground(new java.awt.Color(125, 223, 178));
        principal_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setText("Usuario :");
        principal_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 275, -1, -1));

        pass_lbl.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        pass_lbl.setText("Contraseña :");
        principal_panel.add(pass_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 346, -1, -1));

        titulo_lbl.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        titulo_lbl.setText("Inicie Sesión");
        principal_panel.add(titulo_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        usuario_tf.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        usuario_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuario_tfKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usuario_tfKeyTyped(evt);
            }
        });
        principal_panel.add(usuario_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 278, 270, -1));

        ingresar_btn.setBackground(new java.awt.Color(215, 0, 5));
        ingresar_btn.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        ingresar_btn.setForeground(new java.awt.Color(255, 255, 255));
        ingresar_btn.setText("Ingresar");
        ingresar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_btnActionPerformed(evt);
            }
        });
        principal_panel.add(ingresar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 490, 135, 65));

        contra_pf.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        contra_pf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contra_pfActionPerformed(evt);
            }
        });
        contra_pf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contra_pfKeyTyped(evt);
            }
        });
        principal_panel.add(contra_pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 270, -1));

        olvide_lbl.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        olvide_lbl.setText("Olvide mi Contraseña");
        olvide_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                olvide_lblMouseClicked(evt);
            }
        });
        principal_panel.add(olvide_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        back_lbl.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        back_lbl.setText("Regresar");
        back_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_lblMouseClicked(evt);
            }
        });
        principal_panel.add(back_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, -1));

        correo_tf.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        correo_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                correo_tfKeyTyped(evt);
            }
        });
        principal_panel.add(correo_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 330, 30));

        getContentPane().add(principal_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1030, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultas_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultas_btnActionPerformed
        // TODO add your handling code here:
        Consultas_frm consulta = new Consultas_frm(); // Creo la Instancia del panel
        estetica.AbrirFormulario(principal_panel, consulta); // AbrirFormulaio sirve para abrir paneles en el mismo Jframe y espera AbrirFormulario(Donde lo quiero abrir, El que quiero abrir)
    }//GEN-LAST:event_consultas_btnActionPerformed

    
    
    private void usuarios_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarios_btnActionPerformed
        // TODO add your handling code here:
        Usuarios_frm user = new Usuarios_frm();
        estetica.AbrirFormulario(principal_panel, user);
    }//GEN-LAST:event_usuarios_btnActionPerformed

    
    
    
    private void ingresar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_btnActionPerformed
        // TODO add your handling code here:
        ConexionBD con = new ConexionBD();
        Correo mail = new Correo();
        String[] autoridad;//Toma los valores de inicio de sesion
        autoridad=con.login(usuario_tf.getText(),contra_pf.getText());
        
       if(pass_lbl.getText().equals("Correo: ")){
           if((con.validoRecuperacion(usuario_tf.getText(),correo_tf.getText()))==0){
               JOptionPane.showMessageDialog(null,"El usuario o Correo no son Existentes");
           }
           else{
               con.ObtenerPasssword(usuario_tf.getText(),correo_tf.getText());
               correo_tf.setText("");
               usuario_tf.setText("");
           }
           
       }
       else{
           if(ConexionBD.Nivel_Autoridad!=null){//Solo si el resultado de ingresar mi usuario y contra encuentra un usuario entra en caso que no tira un nulo y hace que no entre al ciclo
            ConexionBD.usuario=usuario_tf.getText();
            if(autoridad[1] == null){
                JOptionPane.showMessageDialog(null,"Primera Sesion"); // Toma la ultima vez que se entro al sistema
            }
            else{
                JOptionPane.showMessageDialog(null,"Ultima Sesión: "+autoridad[1]); // Toma la ultima vez que se entro al sistema
            }
             if(ConexionBD.Estado==1){
                 
            nombre_lbl.setText(autoridad[2]);
            bienvenido_lbl.setVisible(true);
            nombre_lbl.setVisible(true);
                
            home_frm inicio = new home_frm();
            estetica.AbrirFormulario(principal_panel, inicio);
            //Nivel de Administrador
            if(autoridad[0].equals("1")){ //Establezco los niveles de autoridad segun el nivel de Acceso
                consultas_btn.setVisible(true);
                puesto_btn.setVisible(true);
                usuarios_btn.setVisible(true);
                restart_btn.setVisible(true);
                empleados_btn.setVisible(true);
        
                
            }
            //Nivel Alto
            if(ConexionBD.Nivel_Autoridad.equals("2")){
                consultas_btn.setVisible(true);
                puesto_btn.setVisible(true);
                usuarios_btn.setVisible(true);
                restart_btn.setVisible(true);
                
            }
            //Nivel Medio
            if(ConexionBD.Nivel_Autoridad.equals("3")){
                consultas_btn.setVisible(true);
                puesto_btn.setVisible(true);
                usuarios_btn.setVisible(true);
                restart_btn.setVisible(true);
                
            }
            //Nivel Bajo
            if(ConexionBD.Nivel_Autoridad.equals("4")){
                consultas_btn.setVisible(true);
                puesto_btn.setVisible(false);
                usuarios_btn.setVisible(true);
                restart_btn.setVisible(true); 
            }
            }
            else{
                JOptionPane.showMessageDialog(null,"Ese usuario esta inactivo por favor consulte con su Administrador");
            }
            
            
        }
        else{
            JOptionPane.showMessageDialog(null,"Usuario incorrecto o contraseña  erronea");
        }
            
       }
    }//GEN-LAST:event_ingresar_btnActionPerformed

    private void restart_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restart_btnActionPerformed
        // TODO add your handling code here:
        //Boton de Reiniciar
        Principal_frm princi = new Principal_frm();//Creo una nueva instancia del Jframe principal
        this.dispose();//La tiro
        princi.setVisible(true); //Abro la nueva
    }//GEN-LAST:event_restart_btnActionPerformed

    private void puesto_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puesto_btnActionPerformed
        // TODO add your handling code here:
        puesto_frm puesto = new puesto_frm();
        estetica.AbrirFormulario(principal_panel, puesto);
    }//GEN-LAST:event_puesto_btnActionPerformed

    private void olvide_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olvide_lblMouseClicked
        // TODO add your handling code here:
        pass_lbl.setText("Correo: ");
        back_lbl.setVisible(true);
        olvide_lbl.setVisible(false);
        ingresar_btn.setText("Enviar");
        titulo_lbl.setText("Olvido de Contraseña");
        correo_tf.setVisible(true);
        contra_pf.setVisible(false);
         correo_tf.setText("");
        usuario_tf.setText("");
    }//GEN-LAST:event_olvide_lblMouseClicked

    private void back_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_lblMouseClicked
        // TODO add your handling code here:
        pass_lbl.setText("Contraseña: ");
        back_lbl.setVisible(false);
        olvide_lbl.setVisible(true);
        ingresar_btn.setText("Ingresar");
        titulo_lbl.setText("Inicie Sesión");
        correo_tf.setVisible(false);
        contra_pf.setVisible(true);
        contra_pf.setText("");
    }//GEN-LAST:event_back_lblMouseClicked

    private void contra_pfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contra_pfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contra_pfActionPerformed

    private void usuario_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuario_tfKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_usuario_tfKeyPressed

    private void usuario_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuario_tfKeyTyped
        // TODO add your handling code here:
        if (!(Character.isLetter(evt.getKeyChar())) && !(Character.isDigit(evt.getKeyChar())))
        {
            evt.consume();              
        }
        if (usuario_tf.getText().length() >= 30)
        {
            evt.consume();                
        }
    }//GEN-LAST:event_usuario_tfKeyTyped

    private void contra_pfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contra_pfKeyTyped
        // TODO add your handling code here:
        if (!(Character.isLetter(evt.getKeyChar())) && !(Character.isDigit(evt.getKeyChar())))
        {
            evt.consume();              
        }
        if (contra_pf.getPassword().length >= 30)
        {
            evt.consume();                
        }
    }//GEN-LAST:event_contra_pfKeyTyped

    private void correo_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correo_tfKeyTyped
        // TODO add your handling code here:
        if (!(Character.isLetter(evt.getKeyChar())) && !(Character.isDigit(evt.getKeyChar())) && !(evt.getKeyChar()=='.') && !(evt.getKeyChar()=='@'))
        {
            evt.consume();
        }
        if (correo_tf.getText().length() >= 30)
        {
            evt.consume();                
        }
    }//GEN-LAST:event_correo_tfKeyTyped

    private void empleados_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleados_btnActionPerformed
        // TODO add your handling code here:
        Empleados_frm empleado = new Empleados_frm();
        estetica.AbrirFormulario(principal_panel,empleado);
    }//GEN-LAST:event_empleados_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_frm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_lbl;
    private javax.swing.JLabel bienvenido_lbl;
    private javax.swing.JButton consultas_btn;
    private javax.swing.JPasswordField contra_pf;
    private javax.swing.JTextField correo_tf;
    private javax.swing.JButton empleados_btn;
    private javax.swing.JButton ingresar_btn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel left_panel;
    private javax.swing.JLabel nombre_lbl;
    private javax.swing.JLabel olvide_lbl;
    private javax.swing.JLabel pass_lbl;
    private javax.swing.JLayeredPane principal_panel;
    private javax.swing.JButton puesto_btn;
    private javax.swing.JButton restart_btn;
    private javax.swing.JLabel titulo_lbl;
    private javax.swing.JTextField usuario_tf;
    private javax.swing.JButton usuarios_btn;
    // End of variables declaration//GEN-END:variables
}
