/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_recursoshumanos;

/**
 *
 * @author hondu
 */
public class puesto_frm extends javax.swing.JPanel {

    /**
     * Creates new form puesto_frm
     */
    public puesto_frm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        modificarPuesto_btn = new javax.swing.JButton();
        crearPuesto_btn = new javax.swing.JButton();
        puestos_panel = new javax.swing.JLayeredPane();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 7));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modificarPuesto_btn.setBackground(new java.awt.Color(215, 0, 5));
        modificarPuesto_btn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        modificarPuesto_btn.setForeground(new java.awt.Color(255, 255, 255));
        modificarPuesto_btn.setText("Modificar Puesto");
        modificarPuesto_btn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        modificarPuesto_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarPuesto_btnActionPerformed(evt);
            }
        });
        jPanel1.add(modificarPuesto_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 180, 60));

        crearPuesto_btn.setBackground(new java.awt.Color(215, 0, 5));
        crearPuesto_btn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        crearPuesto_btn.setForeground(new java.awt.Color(255, 255, 255));
        crearPuesto_btn.setText("Crear Puesto");
        crearPuesto_btn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        crearPuesto_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPuesto_btnActionPerformed(evt);
            }
        });
        jPanel1.add(crearPuesto_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

        javax.swing.GroupLayout puestos_panelLayout = new javax.swing.GroupLayout(puestos_panel);
        puestos_panel.setLayout(puestos_panelLayout);
        puestos_panelLayout.setHorizontalGroup(
            puestos_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        puestos_panelLayout.setVerticalGroup(
            puestos_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        add(puestos_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1030, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void modificarPuesto_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarPuesto_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarPuesto_btnActionPerformed

    private void crearPuesto_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPuesto_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearPuesto_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearPuesto_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificarPuesto_btn;
    private javax.swing.JLayeredPane puestos_panel;
    // End of variables declaration//GEN-END:variables
}
