/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_recursoshumanos;

/**
 *
 * @author hondu
 */
public class Usuarios_frm extends javax.swing.JPanel {

    private  Design estetica = new Design();
    /**
     * Creates new form Usuarios_frm
     */
    public Usuarios_frm() {
        initComponents();
        if(Integer.parseInt(ConexionBD.Nivel_Autoridad)>=2){
            modificarUsuarios_btn.setVisible(false);
            if(Integer.parseInt(ConexionBD.Nivel_Autoridad)>=3){
            crearUsuarios_btn.setVisible(false);
        }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        crearUsuarios_btn = new javax.swing.JButton();
        modificarUsuarios_btn = new javax.swing.JButton();
        crearUsuarios_btn3 = new javax.swing.JButton();
        usuarios_panel = new javax.swing.JLayeredPane();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 7));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearUsuarios_btn.setBackground(new java.awt.Color(215, 0, 5));
        crearUsuarios_btn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        crearUsuarios_btn.setForeground(new java.awt.Color(255, 255, 255));
        crearUsuarios_btn.setText("Crear Usuario");
        crearUsuarios_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        crearUsuarios_btn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        crearUsuarios_btn.setName(""); // NOI18N
        crearUsuarios_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUsuarios_btnActionPerformed(evt);
            }
        });
        jPanel1.add(crearUsuarios_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 150, 60));
        crearUsuarios_btn.getAccessibleContext().setAccessibleName("Ingresar\n Usuarios");

        modificarUsuarios_btn.setBackground(new java.awt.Color(215, 0, 5));
        modificarUsuarios_btn.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        modificarUsuarios_btn.setForeground(new java.awt.Color(255, 255, 255));
        modificarUsuarios_btn.setText("Modificar Usuarios");
        modificarUsuarios_btn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        modificarUsuarios_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarUsuarios_btnActionPerformed(evt);
            }
        });
        jPanel1.add(modificarUsuarios_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 190, 60));

        crearUsuarios_btn3.setBackground(new java.awt.Color(215, 0, 5));
        crearUsuarios_btn3.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        crearUsuarios_btn3.setForeground(new java.awt.Color(255, 255, 255));
        crearUsuarios_btn3.setText("Cambiar Contraseña");
        crearUsuarios_btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        crearUsuarios_btn3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        crearUsuarios_btn3.setName(""); // NOI18N
        crearUsuarios_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUsuarios_btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(crearUsuarios_btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 60));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));
        add(usuarios_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1030, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void crearUsuarios_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUsuarios_btnActionPerformed
        // TODO add your handling code here:
         nuevoUsuario_frm us = new nuevoUsuario_frm();
         Design estetica = new Design();
         estetica.AbrirFormulario(usuarios_panel, us);
         
    }//GEN-LAST:event_crearUsuarios_btnActionPerformed

    private void modificarUsuarios_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarUsuarios_btnActionPerformed
        // TODO add your handling code here:
         ModificarUsuario_frm us = new ModificarUsuario_frm();
         Design estetica = new Design();
         estetica.AbrirFormulario(usuarios_panel, us);
    }//GEN-LAST:event_modificarUsuarios_btnActionPerformed

    private void crearUsuarios_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUsuarios_btn3ActionPerformed
        // TODO add your handling code here:
        CambiarPassword_frm usu = new CambiarPassword_frm();
        estetica.AbrirFormulario(usuarios_panel, usu);
    }//GEN-LAST:event_crearUsuarios_btn3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearUsuarios_btn;
    private javax.swing.JButton crearUsuarios_btn3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificarUsuarios_btn;
    private javax.swing.JLayeredPane usuarios_panel;
    // End of variables declaration//GEN-END:variables
}
